server {
    listen 80;

    # Redirection des requêtes API vers le conteneur backend
    location /api {
        proxy_pass http://backend:3000;
    }

    # Redirection du reste vers le conteneur frontend
    location / {
        proxy_pass http://frontend:80;
    }
}